---

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: tgbotserver
  namespace: {{ $.Release.Namespace }}
  labels:
    app: tgbotserver

spec:
  selector:
    matchLabels:
      app: tgbotserver
  template:
    metadata:
      name: tgbotserver
      labels:
        app: tgbotserver

    spec:

      volumes:
        - name: tgbotserver
          hostPath:
            path: /opt/tgbotserver/
            type: DirectoryOrCreate

      containers:

        - name: tgbotserver
          image: "{{ $.Values.ImageNameGithubTgBotServer }}:{{ $.Values.ImageTagGithubTgBotServer }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: TELEGRAM_API_ID
              value: "{{ $.Values.TgBotServerApiId }}"
            - name: TELEGRAM_API_HASH
              value: "{{ $.Values.TgBotServerApiHash }}"
          volumeMounts:
            - name: tgbotserver
              mountPath: /tgbotserver/downloads/


